### PR TITLE
Update Bootstrap Address for Mainnet

### PR DESCRIPTION
**Pull request by thelazier**
Dear P2Pool owner,

I would like to open request for add more bootstrap address for Mainnet please kindly provide your p2pool address if you would like to be added or removed.

BTW, I start with adding the address from 12.0 network which already upgraded and running on 12.1 network.
http://dash01.p2poolmining.us:7903/static/
http://p2pool.2sar.ru:7903/static/

### CODE REVIEW

**Comment by ourlink** [comment]
You could add a couple of our other pools addresses too...
dash02.p2poolmining.us:7903
dash03.p2poolmining.us:7903
dash04.p2poolmining.us:7903

All of these pools run independently. Therefore they should provide good bootstrap capabilities to the network.

**Comment by ilsawa** [comment]
crypto.office-on-the.net:7903

**Comment by thelazier** [comment]
Thank you @ourlink , @ilsawa , Your nodes added c6a74a0

**Comment by thelazier** [comment]
@UdjinM6 @schinzelh , I think current set of bootstrap nodes are ready to be merged if you are ok.

**Pull request merged**
