### PR TITLE
Update some improvements

### PR DESCRIPTION
**Pull request by thelazier**
These are improvement updates which should increase p2pool performance, my node is running these already and working fine.

### CODE REVIEW

**Comment by ourlink** [comment]
thelazier - there is an error in your code for **p2pool-dash\p2pool\data.py** @ line #147. In your code you are referencing **_bitcoin_data_** which should be **_dash_data_**.

I made the change in my test environment and now your code executes as expected.

**Comment by thelazier** [comment]
rebased from master branch, remove 8mb size.

**Comment by UdjinM6** [comment]
@chaeplin can you test this pls?

**Comment by chaeplin** [comment]
In testing

**Comment by ourlink** [comment]
Testing with a "LIVE" pool for backwards compatibility... Also on TESTNET

**Comment by ourlink** [comment]
I am seeing a few of these errors intermittently happening;
`Traceback (most recent call last):
  File "/root/p2pool-dash/p2pool/node.py", line 65, in handle_share_hashes
    self.handle_shares([(share, []) for share in shares], peer)
  File "/root/p2pool-dash/p2pool/node.py", line 46, in handle_shares
    self.node.set_best_share()
  File "/root/p2pool-dash/p2pool/node.py", line 297, in set_best_share
    self.best_share_var.set(best)
  File "/root/p2pool-dash/p2pool/util/variable.py", line 74, in set
    self.changed.happened(value)
--- <exception caught here> ---
  File "/root/p2pool-dash/p2pool/util/variable.py", line 42, in happened
    func(*event)
  File "/root/p2pool-dash/p2pool/node.py", line 94, in broadcast_share
    peer.sendShares([share for share in shares if share.peer_addr != peer.addr], self.node.tracker, self.node.known_txs_var.value, include_txs_with=[share_hash])
  File "/root/p2pool-dash/p2pool/p2p.py", line 335, in sendShares
    assert tx_hash in known_txs, 'tried to broadcast share without knowing all its new transactions'
exceptions.AssertionError: tried to broadcast share without knowing all its new transactions
`

**Comment by chaeplin** [comment]
same log here when I two connected node
```
2017-11-01 21:26:25.373910 GOT SHARE! yfyzM58VsmjfbXtTzNrYH14TmJvY3Nn3Ms 09984c28 prev b6d24dba age 13.21s
2017-11-01 21:26:25.473526 > Error while processing Event callbacks:
2017-11-01 21:26:25.473646 > Traceback (most recent call last):
2017-11-01 21:26:25.473697 >   File "/home/coind/p2pool-dash/p2pool/dash/worker_interface.py", line 136, in <lambda>
2017-11-01 21:26:25.473746 >     lambda header, user, coinbase_nonce: handler(header, user, pack.IntType(self._my_bits).pack(nonce) + coinbase_nonce),
2017-11-01 21:26:25.473795 >   File "/home/coind/p2pool-dash/p2pool/work.py", line 465, in got_response
2017-11-01 21:26:25.473838 >     self.node.set_best_share()
2017-11-01 21:26:25.473878 >   File "/home/coind/p2pool-dash/p2pool/node.py", line 297, in set_best_share
2017-11-01 21:26:25.473920 >     self.best_share_var.set(best)
2017-11-01 21:26:25.473959 >   File "/home/coind/p2pool-dash/p2pool/util/variable.py", line 74, in set
2017-11-01 21:26:25.473999 >     self.changed.happened(value)
2017-11-01 21:26:25.474038 > --- <exception caught here> ---
2017-11-01 21:26:25.474076 >   File "/home/coind/p2pool-dash/p2pool/util/variable.py", line 42, in happened
2017-11-01 21:26:25.474140 >     func(*event)
2017-11-01 21:26:25.474182 >   File "/home/coind/p2pool-dash/p2pool/node.py", line 94, in broadcast_share
2017-11-01 21:26:25.474226 >     peer.sendShares([share for share in shares if share.peer_addr != peer.addr], self.node.tracker, self.node.known_txs_var.value, include_txs_with=[share_hash])
2017-11-01 21:26:25.474276 >   File "/home/coind/p2pool-dash/p2pool/p2p.py", line 336, in sendShares
2017-11-01 21:26:25.474318 >     assert tx_hash in known_txs, 'tried to broadcast share without knowing all its new transactions'
2017-11-01 21:26:25.474361 > exceptions.AssertionError: tried to broadcast share without knowing all its new transactions
2017-11-01 21:26:25.684676 Generating a share with 1898609 bytes (127377 new) and 3616 transactions (230 new)

```

**Comment by thelazier** [comment]
@ourlink @chaeplin , This error introduced by #36 , I think current master would also have same errors occurred. It should be fixed by #37

**Comment by chaeplin** [comment]
@thelazier 26 + 37 
```
2017-11-02 17:17:58.708823 Peer sent entire transaction c314e8ad2fc978a89a198e717f2b316cac99252bebd2dab2a386d15302b6cb38 that was already received
2017-11-02 17:18:01.001401 GOT SHARE! yfyzM58VsmjfbXtTzNrYH14TmJvY3Nn3Ms ff1b973d prev becb250a age 26.80s
2017-11-02 17:18:01.280201 > Error while processing Event callbacks:
2017-11-02 17:18:01.280287 > Traceback (most recent call last):
2017-11-02 17:18:01.280590 >   File "/home/coind/p2pool-dash/p2pool/dash/worker_interface.py", line 136, in <lambda>
2017-11-02 17:18:01.280634 >     lambda header, user, coinbase_nonce: handler(header, user, pack.IntType(self._my_bits).pack(nonce) + coinbase_nonce),
2017-11-02 17:18:01.280795 >   File "/home/coind/p2pool-dash/p2pool/work.py", line 465, in got_response
2017-11-02 17:18:01.280941 >     self.node.set_best_share()
2017-11-02 17:18:01.281100 >   File "/home/coind/p2pool-dash/p2pool/node.py", line 297, in set_best_share
2017-11-02 17:18:01.281131 >     self.best_share_var.set(best)
2017-11-02 17:18:01.281157 >   File "/home/coind/p2pool-dash/p2pool/util/variable.py", line 74, in set
2017-11-02 17:18:01.281180 >     self.changed.happened(value)
2017-11-02 17:18:01.281202 > --- <exception caught here> ---
2017-11-02 17:18:01.281226 >   File "/home/coind/p2pool-dash/p2pool/util/variable.py", line 42, in happened
2017-11-02 17:18:01.281398 >     func(*event)
2017-11-02 17:18:01.281428 >   File "/home/coind/p2pool-dash/p2pool/node.py", line 94, in broadcast_share
2017-11-02 17:18:01.281463 >     peer.sendShares([share for share in shares if share.peer_addr != peer.addr], self.node.tracker, self.node.known_txs_var.value, include_txs_with=[share_hash])
2017-11-02 17:18:01.281495 >   File "/home/coind/p2pool-dash/p2pool/p2p.py", line 336, in sendShares
2017-11-02 17:18:01.281524 >     assert tx_hash in known_txs, 'tried to broadcast share without knowing all its new transactions'
2017-11-02 17:18:01.281551 > exceptions.AssertionError: tried to broadcast share without knowing all its new transactions
2017-11-02 17:18:01.757752 Generating a share with 1898990 bytes (346057 new) and 4054 transactions (626 new)
```

**Comment by ourlink** [comment]
I'm running #37, I will let you know how it goes...

**Comment by ourlink** [comment]
That didn't take long.... Same issue with #37!

`Error while processing Event callbacks:
Traceback (most recent call last):
  File "/root/p2pool-dash/p2pool/p2p.py", line 327, in handle_shares
    self.node.handle_shares(result, self)
  File "/root/p2pool-dash/p2pool/node.py", line 46, in handle_shares
    self.node.set_best_share()
  File "/root/p2pool-dash/p2pool/node.py", line 297, in set_best_share
    self.best_share_var.set(best)
  File "/root/p2pool-dash/p2pool/util/variable.py", line 74, in set
    self.changed.happened(value)
--- <exception caught here> ---
  File "/root/p2pool-dash/p2pool/util/variable.py", line 42, in happened
    func(*event)
  File "/root/p2pool-dash/p2pool/node.py", line 94, in broadcast_share
    peer.sendShares([share for share in shares if share.peer_addr != peer.addr], self.node.tracker, self.node.known_txs_var.value, include_txs_with=[share_hash])
  File "/root/p2pool-dash/p2pool/p2p.py", line 335, in sendShares
    assert tx_hash in known_txs, 'tried to broadcast share without knowing all its new transactions'
exceptions.AssertionError: tried to broadcast share without knowing all its new transactions

`

**Comment by thelazier** [comment]
@chaeplin @ourlink , revised #37 , please try 👍

**Comment by chaeplin** [comment]
In testing, from block 20538 ~.
no known_txs so far :)

**Comment by ourlink** [comment]
Running on Node (Dash05 - San Jose), I'll continue to monitor for any issues... Looks good thus far!

**Comment by ourlink** [comment]
Started running #37 from block 764634 thru 764663.. Several of these blocks were P2Pool blocks. No known_txs issues. Other pools running ```dashpay:master``` did show issues, this fix looks like it is working.

**Comment by chaeplin** [comment]
I got this with lots of txs.

```
...
2017-11-05 06:27:27.994687 WARN: Tried to broadcast share without knowing transaction 6ff7b676781b6a89486d3aa06c70eeb1f5230a957fbf9d6bede095b1c5d3db0d
2017-11-05 06:27:27.994779 WARN: Tried to broadcast share without knowing transaction 92ac5d93237213d77ac48ed725cde644da5a16315f4c124caafbd7a53d26b90a
2017-11-05 06:27:28.002589 > Error while processing Event callbacks:
2017-11-05 06:27:28.002716 > Traceback (most recent call last):
2017-11-05 06:27:28.002872 >   File "/home/coind/p2pool-dash/p2pool/dash/worker_interface.py", line 136, in <lambda>
2017-11-05 06:27:28.002991 >     lambda header, user, coinbase_nonce: handler(header, user, pack.IntType(self._my_bits).pack(nonce) + coinbase_nonce),
2017-11-05 06:27:28.003078 >   File "/home/coind/p2pool-dash/p2pool/work.py", line 465, in got_response
2017-11-05 06:27:28.003402 >     self.node.set_best_share()
2017-11-05 06:27:28.003470 >   File "/home/coind/p2pool-dash/p2pool/node.py", line 297, in set_best_share
2017-11-05 06:27:28.003527 >     self.best_share_var.set(best)
2017-11-05 06:27:28.003581 >   File "/home/coind/p2pool-dash/p2pool/util/variable.py", line 74, in set
2017-11-05 06:27:28.003632 >     self.changed.happened(value)
2017-11-05 06:27:28.003684 > --- <exception caught here> ---
2017-11-05 06:27:28.003744 >   File "/home/coind/p2pool-dash/p2pool/util/variable.py", line 42, in happened
2017-11-05 06:27:28.003797 >     func(*event)
2017-11-05 06:27:28.003855 >   File "/home/coind/p2pool-dash/p2pool/node.py", line 94, in broadcast_share
2017-11-05 06:27:28.003903 >     peer.sendShares([share for share in shares if share.peer_addr != peer.addr], self.node.tracker, self.node.known_txs_var.value, include_txs_with=[share_hash])
2017-11-05 06:27:28.003955 >   File "/home/coind/p2pool-dash/p2pool/p2p.py", line 358, in sendShares
2017-11-05 06:27:28.004011 >     raise ValueError('shares have too many txs')
2017-11-05 06:27:28.004066 > exceptions.ValueError: shares have too many txs
2017-11-05 06:27:28.333647 Generating a share with 1997700 bytes (656597 new) and 6506 transactions (1609 new)
2017-11-05 06:27:28.499018 New work for worker yYVvMz2hF3amaJgxHRxC4D9FrwYC8m4vvA! Difficulty: 0.004526 Share difficulty: 0.112259 Block 21423 Total value: 142.988003 tDASH including 4897 transactions
2017-11-05 06:27:35.246179 Generating a share with 1997700 bytes (656597 new) and 6506 transactions (1609 new)
2017-11-05 06:27:35.383694 New work for worker yd97Tdj28mp75Ncsza4EQd5G5TGdQhUWXE! Difficulty: 0.004526 Share difficulty: 0.112259 Block 21423 Total value: 142.988003 tDASH including 4897 transactions
2017-11-05 06:27:35.587865 P2Pool: 7008 shares in chain (7012 verified/7012 total) Peers: 1 (0 incoming)
2017-11-05 06:27:35.588034  Local: 24407kH/s in last 10.0 minutes Local dead on arrival: ~13.8% (11-17%) Expected time to share: 20.8 seconds
2017-11-05 06:27:35.588106  Shares: 904 (6 orphan, 47 dead) Stale rate: ~5.9% (4-8%) Efficiency: ~104.1% (102-106%) Current payout: (0.0000)=0.0000 tDASH
2017-11-05 06:27:35.588193  Pool: 27392kH/s Stale rate: 9.5% Expected time to block: 2.3 minutes
2017-11-05 06:27:35.643425 Peer 192.168.10.1:49318 says protocol version is 1500, client version 96a74ed
```

**Comment by thelazier** [comment]
@chaeplin please try 95f7d05 :)

**Comment by chaeplin** [comment]
form 21496,  https://github.com/dashpay/p2pool-dash/commit/95f7d051ee1a98f71168bb5954951a8ff98cb64f no error

**Comment by chaeplin** [comment]
at block 21890
```
2017-11-06 02:56:23.631161 Transaction 8e25a362ce950da0cfd8dc91a16c826a531cbd42399832f6b963cf35b023d0ef rescued from peer latency cache!
2017-11-06 02:56:23.631217 Transaction 252fe37e4ab2e1dc05160e15334276bd444e05ee5b24ee3f78ee6fb2f8ffccef rescued from peer latency cache!
2017-11-06 02:56:23.631366 Transaction fbd436ef08764d84e06b023cf0266719615a04e39447d1c2b13e3c9aeca9c6ef rescued from peer latency cache!
2017-11-06 02:56:23.631424 Transaction 4714554fa0455e04d01eccd64958620618784e96233f041a730222417966b7ef rescued from peer latency cache!
2017-11-06 02:56:23.631481 > Peer referenced unknown transaction 75774b9db4447a7f9bd524f3295acc67d375672aa8f853866ef7cbd63198bae7, disconnecting
2017-11-06 02:56:23.658049 Lost peer 192.168.10.1:61716 - Connection was aborted locally, using.
2017-11-06 02:56:24.253357 Peer 192.168.10.1:8437 says protocol version is 1500, client version 96a74ed-dirty
2017-11-06 02:56:24.253524 Incoming connection from peer 192.168.10.1:8437 established. p2pool version: 1500 '96a74ed-dirty'
2017-11-06 02:56:24.397063 RECV version dc0500000000000000000000000000000000000000000000000000000000ffffc0a80a0f4a37000000000000000000000000000000000000ffffc0a80a0120f5e6d0443dd152a68d0d393661373465642d64697274790100000062c1b912f77b0b861796...
2017-11-06 02:56:24.410299 > Error handling message: (see RECV line)
2017-11-06 02:56:24.410399 > Traceback (most recent call last):
2017-11-06 02:56:24.410584 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 214, in doRead
2017-11-06 02:56:24.410695 >     return self._dataReceived(data)
2017-11-06 02:56:24.410799 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 220, in _dataReceived
2017-11-06 02:56:24.410916 >     rval = self.protocol.dataReceived(data)
2017-11-06 02:56:24.410958 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 27, in dataReceived
2017-11-06 02:56:24.411065 >     self.dataReceived2(data)
2017-11-06 02:56:24.411100 >   File "/home/coind/p2pool-dash/p2pool/util/datachunker.py", line 40, in _DataChunker
2017-11-06 02:56:24.411180 >     wants = receiver.send(buf.get(wants))
2017-11-06 02:56:24.411210 > --- <exception caught here> ---
2017-11-06 02:56:24.411241 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 57, in dataReceiver
2017-11-06 02:56:24.411268 >     self.packetReceived(command, type_.unpack(payload, self.ignore_trailing_payload))
2017-11-06 02:56:24.411295 >   File "/home/coind/p2pool-dash/p2pool/p2p.py", line 91, in packetReceived
2017-11-06 02:56:24.411323 >     p2protocol.Protocol.packetReceived(self, command, payload2)
2017-11-06 02:56:24.411364 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 71, in packetReceived
2017-11-06 02:56:24.411409 >     handler(**payload2)
2017-11-06 02:56:24.411467 >   File "/home/coind/p2pool-dash/p2pool/p2p.py", line 223, in handle_version
2017-11-06 02:56:24.411503 >     self.send_have_tx(tx_hashes=self.node.known_txs_var.value.keys())
2017-11-06 02:56:24.411532 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 102, in <lambda>
2017-11-06 02:56:24.411562 >     return lambda **payload2: self.sendPacket(command, payload2)
2017-11-06 02:56:24.411589 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 93, in sendPacket
2017-11-06 02:56:24.411616 >     raise TooLong('payload too long')
2017-11-06 02:56:24.411643 > p2pool.util.p2protocol.TooLong: payload too long
2017-11-06 02:56:24.413996 Lost peer 192.168.10.1:8437 - Connection was aborted locally, using.
2017-11-06 02:56:24.414447 > in handle_share_hashes:
2017-11-06 02:56:24.414517 > Traceback (most recent call last):
2017-11-06 02:56:24.414566 > Failure: twisted.internet.error.ConnectionAborted: Connection was aborted locally, using.
2017-11-06 02:56:26.507876 Peer 192.168.10.1:8440 says protocol version is 1500, client version 96a74ed-dirty
2017-11-06 02:56:26.508018 Incoming connection from peer 192.168.10.1:8440 established. p2pool version: 1500 '96a74ed-dirty'
2017-11-06 02:56:26.644191 RECV version dc0500000000000000000000000000000000000000000000000000000000ffffc0a80a0f4a37000000000000000000000000000000000000ffffc0a80a0120f8e6d0443dd152a68d0d393661373465642d64697274790100000062c1b912f77b0b861796...
```


```
2017-11-06 03:00:59.631810 Peer 192.168.10.1:9510 says protocol version is 1500, client version 96a74ed-dirty
2017-11-06 03:00:59.631994 Incoming connection from peer 192.168.10.1:9510 established. p2pool version: 1500 '96a74ed-dirty'
2017-11-06 03:00:59.819012 RECV version dc0500000000000000000000000000000000000000000000000000000000ffffc0a80a0f4a37000000000000000000000000000000000000ffffc0a80a012526e6d0443dd152a68d0d393661373465642d646972747901000000fb7bb8c331329c0d5059...
2017-11-06 03:00:59.819352 > Error handling message: (see RECV line)
2017-11-06 03:00:59.819437 > Traceback (most recent call last):
2017-11-06 03:00:59.819487 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 214, in doRead
2017-11-06 03:00:59.819531 >     return self._dataReceived(data)
2017-11-06 03:00:59.819574 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 220, in _dataReceived
2017-11-06 03:00:59.819620 >     rval = self.protocol.dataReceived(data)
2017-11-06 03:00:59.819660 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 27, in dataReceived
2017-11-06 03:00:59.819702 >     self.dataReceived2(data)
2017-11-06 03:00:59.819752 >   File "/home/coind/p2pool-dash/p2pool/util/datachunker.py", line 40, in _DataChunker
2017-11-06 03:00:59.819814 >     wants = receiver.send(buf.get(wants))
2017-11-06 03:00:59.819880 > --- <exception caught here> ---
2017-11-06 03:00:59.819927 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 57, in dataReceiver
2017-11-06 03:00:59.819971 >     self.packetReceived(command, type_.unpack(payload, self.ignore_trailing_payload))
2017-11-06 03:00:59.820024 >   File "/home/coind/p2pool-dash/p2pool/p2p.py", line 91, in packetReceived
2017-11-06 03:00:59.820076 >     p2protocol.Protocol.packetReceived(self, command, payload2)
2017-11-06 03:00:59.820123 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 71, in packetReceived
2017-11-06 03:00:59.820171 >     handler(**payload2)
2017-11-06 03:00:59.820225 >   File "/home/coind/p2pool-dash/p2pool/p2p.py", line 223, in handle_version
2017-11-06 03:00:59.820276 >     self.send_have_tx(tx_hashes=self.node.known_txs_var.value.keys())
2017-11-06 03:00:59.820323 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 102, in <lambda>
2017-11-06 03:00:59.820371 >     return lambda **payload2: self.sendPacket(command, payload2)
2017-11-06 03:00:59.820416 >   File "/home/coind/p2pool-dash/p2pool/util/p2protocol.py", line 93, in sendPacket
2017-11-06 03:00:59.820475 >     raise TooLong('payload too long')
2017-11-06 03:00:59.820520 > p2pool.util.p2protocol.TooLong: payload too long
2017-11-06 03:00:59.822163 Lost peer 192.168.10.1:9510 - Connection was aborted locally, using.
2017-11-06 03:00:59.822330 > in handle_share_hashes:
2017-11-06 03:00:59.822410 > Traceback (most recent call last):
2017-11-06 03:00:59.822460 > Failure: twisted.internet.error.ConnectionAborted: Connection was aborted locally, using.
```

```
2017-11-06 03:00:57.987352 Peer 192.168.10.15:48614 says protocol version is 1500, client version b124f9f-dirty
2017-11-06 03:00:57.987514 Incoming connection from peer 192.168.10.15:48614 established. p2pool version: 1500 'b124f9f-dirty'
2017-11-06 03:00:58.383389 > Error while processing Event callbacks:
2017-11-06 03:00:58.383483 > Traceback (most recent call last):
2017-11-06 03:00:58.383513 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
2017-11-06 03:00:58.383541 >     self._disconnectSelectable(selectable, why, inRead)
2017-11-06 03:00:58.383566 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 260, in _disconnectSelectable
2017-11-06 03:00:58.383588 >     selectable.connectionLost(f)
2017-11-06 03:00:58.383612 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 298, in connectionLost
2017-11-06 03:00:58.383633 >     protocol.connectionLost(reason)
2017-11-06 03:00:58.383652 >   File "/home/coind/p2pool-dash/p2pool/p2p.py", line 476, in connectionLost
2017-11-06 03:00:58.383671 >     self.connection_lost_event.happened()
2017-11-06 03:00:58.383693 > --- <exception caught here> ---
2017-11-06 03:00:58.383716 >   File "/home/coind/p2pool-dash/p2pool/util/variable.py", line 42, in happened
2017-11-06 03:00:58.383735 >     func(*event)
2017-11-06 03:00:58.383753 >   File "/home/coind/p2pool-dash/p2pool/p2p.py", line 221, in <lambda>
2017-11-06 03:00:58.383772 >     self.connection_lost_event.watch(lambda: self.node.known_txs_var.transitioned.unwatch(watch_id2))
2017-11-06 03:00:58.383792 >   File "/home/coind/p2pool-dash/p2pool/util/variable.py", line 26, in unwatch
2017-11-06 03:00:58.383813 >     self.observers.pop(id)
2017-11-06 03:00:58.383832 > exceptions.KeyError: 21
2017-11-06 03:00:58.383897 Lost peer 192.168.10.15:48614 - Connection to the other side was lost in a non-clean fashion.
2017-11-06 03:00:58.384016 > in handle_share_hashes:
2017-11-06 03:00:58.384053 > Traceback (most recent call last):
2017-11-06 03:00:58.384091 > Failure: twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.
```

**Comment by UdjinM6** [comment]
Hmm... We probably should take our time to test this properly. I'd postpone this patch till later - don't want to mess 12.2 release up because of potential 10% performance increase.

**Comment by thelazier** [comment]
@chaeplin , from your logs, payload size 2M is not enough. please try 8M from #38

**Comment by thelazier** [comment]
@UdjinM6 , agree to take time to test properly but some patches like #37 #38 would need to apply to fix master branch since the errors from stress testing by @chaeplin and @ourlink are mostly not directly related to this 10% performance improvement PR.

**Comment by UdjinM6** [comment]
>the errors from stress testing by @chaeplin and @ourlink are mostly not directly related to this 10% performance improvement PR.

Yep, it's a good idea to separate these fixes I guess

**Pull request closed without merging**
