### PR TITLE
Update to DashCore 0.12.3 commands

### PR DESCRIPTION
**Pull request by thelazier**
based on https://github.com/p2pool/p2pool/pull/367

### CODE REVIEW

**Comment by nmarley** [comment]
@UdjinM6 Ok to merge this one ?

**Comment by UdjinM6** [comment]
Yep. Maybe we should update https://github.com/dashpay/p2pool-dash/blob/master/README.md as well though, specifically change `Dashd >=0.12.1.0` to `Dashd >=0.12.3.0`?

**Comment by nmarley** [comment]
Should it be `Dashd >=0.12.2.0` until the 0.12.3.1 point release? Otherwise we'd be changing it now, for an as-yet unreleased version.

**Comment by UdjinM6** [comment]
@nmarley Agree

re-utACK 3ceffb6

**Pull request merged**
